version: '3.9'

services:
  mysql:
    image: mysql:8

    container_name: interior-mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: interiordb
      MYSQL_ROOT_HOST: "%"

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: